model: LSTMNet
data_dir: C:\Users\disen\Desktop\PRproject\Final Project data\Final Project data 
log: wandb
wandb_api_key: adeb2c72bdb4d569ebb9cc40c9129260f5beac58  
validation: [cross]
save_best: True # save model based on best validation set score
target_metric: accuracy  # save based on: accuracy / f1
log_best: True # log best score in the end of the run
error_analysis: False 
n_sensors: 248 
n_timesteps: 35624
downsample: 4
window_size: 800
out_channels: 64
kernel_size: 5
stride: 1
padding: 0
negative_slope: 0.01 
pooling_size: 2
num_classes: 4
n_layers: 4
lr: 0.0002
warmup_epochs: 5
epochs: 60
steps_per_epoch: 2
batch_size: 8
lstm_hidden_size: 800
name: lstm
#